# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
orbs:
  gcp-gke: circleci/gcp-gke@1.0.4
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/PokemonAPI # The shadowJar archive name always begins with the directory name by default
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests!
      - run: ./gradlew test
  push_image:
    machine: true
    working_directory: ~/PokemonAPI
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build Jar
          command: ./gradlew shadowJar
      - run:
          name: Build and push docker
          command: |
            docker build -t chrismarquez/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push chrismarquez/$IMAGE_NAME:$TAG
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - run:
          name: Docker Hub Login
          command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: cluster-1
          deployment: pokemon-api-depl
          container: pokemon-api
          image: docker.io/chrismarquez/$IMAGE_NAME # change version when updating
          tag: $TAG

workflows:
  version: 2
  build-push_image-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - push_image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - push_image
          filters:
            branches:
              only:
                - master