apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api-deployment
spec:
  selector:
    matchLabels:
      app: pokemon-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
        - image: docker.io/chrismarquez/pokemon-api:latest
          name: pokemon-api-instance
          ports:
            - containerPort: 8080