openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/chrismarquez7/PokemonAPI/1.0.0
  - url: 'http'
paths: